name: WayStones
version: '${project.version}'
main: com.danikvitek.waystone.WayStonesPlugin
api-version: 1.17
depend: [ ItemsAdder, ProtocolLib, ScalaSupport ]
authors: [ Danik_Vitek ]

description: "This plugin lets players to create waystones. 
              After discovering a few waystones, player will be able to teleport from one to another.
              Teleportation is visualized in several ways: 
              - far presence (foreign players will see the position of those who is going to teleport to their waystone), 
              - destination preview (phantom blocks ae shown to the player, displaying the scene, that is located
              at the destination point)."