name: Entities
version: '$A1.0'
main: org.foton.entities.EntitiesLauncher
api-version: 1.17
authors: [ Denery ]

commands:
  erspawn:
    description: Spawn entity if its ID is registered in EntityRegistryLib.
    usage: /<command>
permissions:
  "foton.commands.erspawn":
    description: A player may use the spawnmodel command
    default: op